---
language: python # (Ansible)

sudo: required

branches:
  except:
    - /^experimental\/.*$/

env:
  global:
    - TIMEOUT=2250

addons:
  apt:
    sources:
      - debian-sid

before_install:

  # currently nothing

install:

  # Nothing for now

before_script:

  # Nothing for now

script:

  # Do testing
  - echo "Hello - start testing"
  - interrupt.sh &

after_script:
  # After-script also run on fail
  - echo "Running cleanup"

