name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        ANDERS_GH_REPO: ${{github.repository}}
        ANDERS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run my bash script
      run: ./script_1.sh
